A=input("Type a noun")
B=input("Type a ajective ")
C=input("type a place")
D=input("type a verb")
E=input("type a famous person")
F=input("type a verb")
print(f"As you walk in the park you see a {A}")
print(f"You turn to your friend and say 'Wow that is a {B} {A}")
print(f"You and your friend walk to {C}")
print(f"As you are there you {D}")
print(f"Your friend then leaves with {E} to {F}")